### ISSUE TITLE
Error when the parent property of a child property is a null

### ISSUE THREAD

**Issue by pyrostrex** [bhoriuchi/vue-deepset#7]
Example data: 

```js
{
  fields: {
    propertyA: null
  }
}
```

Example html used:

```html
<input v-model="model['propertyA.childPropertyA']" />
```

Example of computed (same as example):

```js
model: {
  return this.$deepModel(this.fields);
}
```
Error:

```
Error in render function: "TypeError: Cannot convert undefined or null to object"
```

Expected json output:

```
{
  fields: {
    propertyA: {}
  }
}
```

Thank you for this wonderful library.

**Comment by bhoriuchi** [comment]
I will look into this as soon as I can. Thanks!

**Comment by bhoriuchi** [comment]
This has been resolved with a null check in the `vueSet` method. See source 

Original
https://github.com/bhoriuchi/vue-deepset/blob/940d0c9e7d135323456ae155793e0ee3b878e323/src/vue-deepset.js#L20

Updated
https://github.com/bhoriuchi/vue-deepset/blob/1360559ead3dedea7946fa9df641b619fa4d9b08/src/vue-deepset.js#L20-L22

v0.5.2 has been published to npm with the fix.

Additionally setting the property to `undefined` instead of `null` would have probably worked in the previous version. The current fix could cause issue if the developer tries set a higher path to `null` and another piece of code tries to set a lower path, the lower path will always win. This is probably the most desired behavior which is why I went ahead and published this change.
